import "./globals.css";
import { Inter } from "next/font/google";
import LocalFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./_components/theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const product = LocalFont({
  src: "../public/fonts/product.ttf",
  variable: "--font-product",
});

const cals = LocalFont({
  src: "../public/fonts/cals.ttf",
  variable: "--font-cals",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, cals.variable, product.variable)}>
        <ClerkProvider>
          <ThemeProvider  attribute="class">
            {children}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
